[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y wget unzip gnupg2",
    "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-archive-keyring.gpg",
    "echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-archive-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list",
    "apt-get update",
    "apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1",
    "CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+\\.[0-9]+\\.[0-9]+')",
    "wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip",
    "unzip /tmp/chromedriver.zip -d /tmp/",
    "mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver",
    "chmod +x /usr/local/bin/chromedriver"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python 9bot.py"

[variables]
CHROME_PATH = "/usr/bin/google-chrome"