[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y wget unzip",
  "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -",
  "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google.list",
  "apt-get update",
  "apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1",
  "wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/linux64/chromedriver-linux64.zip",
  "unzip /tmp/chromedriver.zip -d /tmp/",
  "mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver",
  "chmod +x /usr/local/bin/chromedriver"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python 9bot.py"

[environment]
CHROME_PATH = "/usr/bin/google-chrome"